export const IMG_LINK = "https://flowbite.com/docs/images/logo.svg"
export const HEADER_IMG = "https://static.vecteezy.com/system/resources/previews/033/108/404/non_2x/cloud-cosmic-banner-background-free-photo.jpg"
export const ABOUT_IMG = "https://images.unsplash.com/photo-1531973576160-7125cd663d86"
export const TEAM_IMG1 = "https://flowbite.s3.amazonaws.com/blocks/marketing-ui/avatars/bonnie-green.png"
export const TEAM_IMG2 = "https://flowbite.s3.amazonaws.com/blocks/marketing-ui/avatars/jese-leos.png"
export const TEAM_IMG3 = "https://flowbite.s3.amazonaws.com/blocks/marketing-ui/avatars/michael-gouch.png"
export const TEAM_IMG4 = "https://flowbite.s3.amazonaws.com/blocks/marketing-ui/avatars/sofia-mcguire.png"